---
- name: "Check for 64-bit"
  fail: msg="Must be install 64-bit"
  when: ansible_architecture != "x86_64"

- import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: geoip.yml

- import_tasks: user.yml

- import_tasks: dist.yml
  when: cif_build_sdist is undefined or cif_build_sdist == ""

- import_tasks: sdist.yml
  when: cif_build_sdist is defined and cif_build_sdist != ""

- import_tasks: install.yml

- import_tasks: fm/main.yml
  when: cif_fm_enabled

- import_tasks: router/main.yml
  when: cif_router_enabled